# -*- coding: utf-8 -*-
"""classify_pros_and_cons.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z93Gh5goZ-wqP0t4t1lhMsx2azJImYwE
"""

def classify_pros_and_cons(sentences_with_ratings):
    """
    별점을 기준으로 문장 단위 장점(4~5점)과 단점(1~3점) 분류.
    """
    pros = [sentence for sentence, stars in sentences_with_ratings if stars >= 4]
    cons = [sentence for sentence, stars in sentences_with_ratings if stars <= 3]
    return pros, cons
