# -*- coding: utf-8 -*-
"""calculate_average_rating.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T39_YbCYUhS4qp4Ta8rgEHqcewgAJzyR
"""

def calculate_average_rating(star_ratings):
    """
    별점의 평균 계산.
    """
    return sum(star_ratings) / len(star_ratings)